name: Python CI

# Run this workflow every time a new commit pushed to your repository
on: [pull_request]

jobs:
  run-unit-tests:

    name: Run all unit tests in code base
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.8

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: gtsfm-v1
        environment-file: environment_linux.yml
        python-version: 3.8
    - name: Python tests and checks
      shell: bash -l {0}
      run: |
        pip install pytest-cov
        conda info --envs
        bash .github/scripts/python.sh
    - name: React-Three-Fiber app tests
      run: |
        cd rtf_vis_tool && npm install && npm test a
        
